name: passman
description: A simple, cross-platform password manager.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43q
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For generating unique timestamp based IDs for every credential.
  uuid: ^3.0.3
  # Dependencies for the Moor persistence library, for storage using SQLite
  # in all supported platforms.
  moor: ^4.2.1
  sqlite3_flutter_libs: ^0.4.1
  path: ^1.8.0
  path_provider: ^2.0.1
  # The symmetric/assymetric encryption library.
  encrypt: ^5.0.0
  # Library for providing password based key derivation functions.
  pinenacl: ^0.2.0
  # Allows support for scaling/resizing the application contents as per the
  # defined breakpoints.
  responsive_framework: ^0.1.0
  # A simple animated number picker widget.
  numberpicker: ^2.1.1
  # The Neumorphic theming library.
  flutter_neumorphic: ^3.1.0
  # A simple and powerful state management library.
  provider: ^5.0.0
  # Library for multi-platform clipboard support.
  clipboard: ^0.1.3
  # Multi-platform basic data persistence solution.
  shared_preferences: ^2.0.5
  # Simple dynamic theming library.
  easy_dynamic_theme: ^2.0.0
  # Launcher to redirect to URLs.
  url_launcher: ^6.0.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^4.2.1
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.3
  moor_db_viewer: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

    - family: Fira Sans Condensed
      fonts:
        - asset: assets/fonts/FiraSansCondensed-Regular.ttf
        - asset: assets/fonts/FiraSansCondensed-Bold.ttf
          weight: 700
          
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#181818"
  image: "assets/images/logo.png"
  web: false

